EBIvariation/eva-pipeline

- variants_statistics.py
Just the first step, lacks the loading.
> added variants stats creation.

- variants_statistics.py
It only lacks the name retrieval from the luigi.LocalTarget object for the load command line.
> Developed on stats loading, but not finished

- variants_statistics.py
tested stats creation and loading.
> fixed "complete" method in variants stats creation

- src/main/java/embl/ebi/variation/eva/VariantJobsArgs.java
- src/main/java/embl/ebi/variation/eva/pipeline/jobs/VariantAnnotConfiguration.java
- src/main/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfiguration.java
- src/main/java/embl/ebi/variation/eva/pipeline/jobs/VariantStatsConfiguration.java
- src/main/resources/application.properties
- src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationPipingTest.java
- src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationTest.java
- src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantConfigurationWorkflowTest.java
- src/test/java/embl/ebi/variation/eva/pipeline/jobs/VariantWorkflowConfig.java
- src/test/resources/variantConfigurationWorkflow.properties
Implementation of dynamic workflow 
(to be tested)
EVA-189
> Implementation of dynamic workflow - EVA-189

- README.md
- examples/load-aggregated-vcf.properties
- examples/load-genotyped-vcf.properties
- src/main/java/uk/ac/ebi/eva/pipeline/configuration/VariantJobsArgs.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantsStatsCreate.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantsStatsLoad.java
- src/main/resources/application.properties
- src/test/java/uk/ac/ebi/eva/pipeline/configuration/CommonConfig.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/VariantStatsConfigurationTest.java
- src/test/resources/annotation.properties
- src/test/resources/initialize-database.properties
- src/test/resources/variantConfiguration.properties
- src/test/resources/variantConfigurationWorkflow.properties
> EVA-213 allow to specify the path for statistics files

- README.md
- examples/application.properties
- pom.xml
- src/main/resources/application.properties
- src/test/resources/logback-test.xml
Tagging release 2.0-beta1, including first version of the Spring Batch pipeline:
* Transform: OpenGCA 0.5
* Load: OpenCGA 0.5
* Statistics: OpenCGA 0.5, only for population "ALL"
* Annotation: VEP + own code
> Release 2.0-beta1

- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/AggregatedVcfLineMapper.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VcfLineMapper.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/readers/AggregatedVcfReader.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/AggregatedVcfReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/VcfHeaderReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/VcfReaderTest.java
- src/test/java/uk/ac/ebi/eva/test/utils/JobTestUtils.java
Complete spring-based VcfReaders. Add support for aggregated VCFs
> EVA-25 Add AggregatedVcfReader and AggregatedVcfLineMapper

- src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriter.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriterTest.java
Bug fix for multiple call of MongoVariantwriter
> bugFix_mongoWriter_multipleCalls

- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsFilesNameValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/OutputDirStatisticsValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/StatisticsOverwriteValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/PopulationStatisticsLoaderStepParametersValidator.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/ConfigRestartabilityAllowValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsFilesNameValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsVariantsNameValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbNameValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputFastaValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputStudyIdValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputVcfIdValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/OutputDirAnnotationValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/OutputDirStatisticsValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/StatisticsOverwriteValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/VepCachePathValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/VepCacheSpeciesValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/VepCacheVersionValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/VepNumForksValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/VepPathValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/PopulationStatisticsLoaderStepParametersValidatorTest.java
* New classes for validating the files collection name, the output directory for statistics, and whether to overwrite existing statistics.
* New `PopulationStatisticsLoaderStepParametersValidator` class for validation of all the arguments required for that step.
* Import clean up and usage of `TestFileUtils` in test classes.
> EVA-538 Job parameters validation for population statistics store step

- src/main/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReader.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriter.java
- src/main/java/uk/ac/ebi/eva/pipeline/listeners/SkippedItemListener.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriterTest.java
The unique index on { chr : 1, start : 1, end : 1, ref : 1, alt : 1 } not generated yet.
(To discuss if we need to move the index generation into a beforeRead listener)
> VariantsIndexes_EVA-550

- src/main/java/uk/ac/ebi/eva/commons/models/data/VariantSourceEntity.java
- src/main/java/uk/ac/ebi/eva/pipeline/configuration/BeanNames.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/readers/VcfHeaderReader.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantSourceEntityMongoWriter.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/FileLoaderStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/JobOptions.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/AggregatedVcfReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/UnwindingItemReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/UnwindingItemStreamReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/VcfHeaderReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/VcfReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantSourceEntityMongoWriterTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStepTest.java
> EVA-587 add the writing of file metadata into the "files" collection

- src/main/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReader.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriter.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriterTest.java
> BugFix:Create index on annot.ct.so instead of annot only

- src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/VcfReaderConfiguration.java
- src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/VariantWriterConfiguration.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/AggregatedVcfLineMapper.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantAggregatedVcfFactory.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfEVSFactory.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfExacFactory.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactory.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VcfLineMapper.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/readers/AggregatedVcfReader.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/readers/VcfReader.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/DatabaseParameters.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/InputParameters.java
- src/test/java/uk/ac/ebi/eva/pipeline/ApplicationTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantAggregatedVcfFactoryTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfEVSFactoryTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfExacFactoryTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactoryTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/AggregatedVcfReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/UnwindingItemReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/UnwindingItemStreamReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/VcfReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStepTest.java
- src/test/java/uk/ac/ebi/eva/test/configuration/BatchTestConfiguration.java
- src/test/resources/test-mongo.properties
-Use JobParameters in variant loader step
-Refactored VariantSource, now reader uses the minimun parameters required.
> EVA-520 Use JobParameters in variant loader step

- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/VepAnnotationGeneratorStep.java
- src/main/java/uk/ac/ebi/eva/utils/VepUtils.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/AnnotationJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepAnnotationGeneratorStepTest.java
- src/test/java/uk/ac/ebi/eva/utils/EvaJobParameterBuilder.java
> Use JobParameters in VEP run step - EVA-594

- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/FileLoaderStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/DatabaseParameters.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/InputParameters.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStepTest.java
- src/test/java/uk/ac/ebi/eva/utils/EvaJobParameterBuilder.java
The main change is in  src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/FileLoaderStep.java and its test.
> EVA-608 Use JobParameters in VCF header loader step

- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/AggregatedVcfJobParametersValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/FileLoaderStepParametersValidator.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/AggregatedVcfJobParametersValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/FileLoaderStepParametersValidatorTest.java
add a jobParameters validator for the full job of aggregatedVcf. add the validator test as well.
Should we add a required validator for the ANNOTATION_SKIP parameter?
> EVA-598 add validation for aggregatedVcfJob

- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/VepAnnotationGeneratorStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/AnnotationParameter.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/AnnotationParameters.java
Tasklet parameters retieved from autowired container and not from chunkContext
> EVA-594 VepGeneration_jobParameter_improvement2

- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/GenotypedVcfJobParametersValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/PopulationStatisticsLoaderStepParametersValidator.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/GenotypedVcfJobParametersValidatorTest.java
Basically it's the same as AggregatedVcfJobParametersValidator but adding the statistics-related parameters.
> EVA-519 add GenotypedVcfJobParametersValidator and test

- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/PopulationStatisticsLoaderStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/ParametersFromProperties.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStepTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsGeneratorStepTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsLoaderStepTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStepTest.java
- src/test/java/uk/ac/ebi/eva/utils/EvaJobParameterBuilder.java
The summary is that I removed JobOptions from PopulationStatisticsLoaderStep, using the containers that inject the jobParameters
> EVA-597 Use JobParameters in statistics loader step

- src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/NonAnnotatedVariantsMongoReaderConfiguration.java
- src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/VepInputFlatFileWriterConfiguration.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/AnnotationJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepInputGeneratorStepTest.java
- src/test/resources/annotation-job.properties
- src/test/resources/vep-input-generator-step.properties
Use JobParameters in VEP input generation step - EVA-593
> Use JobParameters in VEP input generation step - EVA-593

- src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/GeneReaderConfiguration.java
- src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/GeneWriterConfiguration.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/GeneLoaderStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/IndexesGeneratorStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/DatabaseParameters.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/InputParameters.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsFeaturesNameValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputGtfValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/GeneLoaderStepParametersValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/IndexesGeneratorStepParametersValidator.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/IndexesGeneratorStepTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsFeaturesNameValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputGtfValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/GeneLoaderStepParametersValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/IndexesGeneratorStepParametersValidatorTest.java
- src/test/java/uk/ac/ebi/eva/utils/EvaJobParameterBuilder.java
the job includes two steps:
- GeneLoaderStep
- CreateDatabaseIndexesStep
added also parameter validators for both steps
> EVA-635 Use JobParameters in DatabaseInitializationJob

- README.md
More user-friendly description of the project, focusing a bit less in the technical details and explaining what does the pipeline do, which information does it store, etc. Some links to related projects added for illustration purposes.
Included details on how to install the dependencies (Mongo, VEP, Biodata and OpenCGA) and build the pipeline code.
> EVA-231 Updated project description and build instructions

- src/main/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/AnnotationJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/DatabaseInitializationJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/ParametersFromProperties.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/ConfigRestartabilityAllowValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsFeaturesNameValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsFilesNameValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbCollectionsVariantsNameValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/DbNameValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputStudyIdValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputStudyNameValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputStudyTypeValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputVcfAggregationValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputVcfIdValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/ParametersValidatorUtil.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/StatisticsOverwriteValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/VepCacheSpeciesValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/VepCacheVersionValidator.java
- src/test/java/uk/ac/ebi/eva/pipeline/ApplicationTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/InputStudyNameValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/ParametersValidatorUtilTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/GenotypedVcfJobParametersValidatorTest.java
- src/test/java/uk/ac/ebi/eva/utils/EvaJobParameterBuilder.java
- JobParametersValidator objects connected into Job objects;
- Extra checks added for non ascii characters and line separator;
> EVA-644 - JobParamsCornerCases

- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/AggregatedVcfLineMapper.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfEVSFactory.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfExacFactory.java
- src/main/java/uk/ac/ebi/eva/utils/FileUtils.java
it seems it's not possible to use a resource from within the jar as a regular file: http://stackoverflow.com/a/18055478/2375586
> fix bug: using aggregate mapping from resources

- examples/drop-study-job.properties
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/DropStudyJob.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/FilesByStudyDropperStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/PullFilesAndStatisticsFromVariantGivenStudyIdStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/SingleStudyVariantsDropperStep.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/DropStudyJobParametersValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/DropFilesByStudyStepValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/DropSingleStudyVariantsStepValidator.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/PullFilesAndStatisticsByStudyStepValidator.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReaderTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/DropStudyJobTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/DropFilesByStudyStepTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/DropSingleStudyVariantsStepTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PullFilesAndStatisticsByStudyStepTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/DropStudyJobParametersValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/DropFilesByStudyStepValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/DropSingleStudyVariantsStepValidatorTest.java
- src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/PullFilesAndStatisticsByStudyStepValidatorTest.java
- src/test/java/uk/ac/ebi/eva/test/rules/TemporaryMongoRule.java
- src/test/java/uk/ac/ebi/eva/test/utils/DropStudyJobTestUtils.java
- src/test/java/uk/ac/ebi/eva/test/utils/JobTestUtils.java
- src/test/java/uk/ac/ebi/eva/utils/EvaCommandLineBuilder.java
- job wiring up the three steps (dropSingleStudyVariantsStep, dropVariantsAndStatisticsByStudyStep, dropVariantsAndStatisticsByStudyStep)
- job test
- parameters validator for the job (and validator test)
- parameters validators for the three steps (and validator tests)
- some general improvements (extracting common methods and improving logs)
> EVA-680 Job to drop study from Mongo

- src/main/java/uk/ac/ebi/eva/commons/models/data/Variant.java
- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactory.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStep.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactoryTest.java
Note:
- Variant.setChromosome does not remove the "chr" anymore. The only place that should do that is the factory.
> EVA-461 Remove Chr and chr prefix in CHROM column during loading

- src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactory.java
- src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactoryTest.java
VariantVcfFactory.java, VariantVCFFactoryTest.java - Ignore variant IDs submitted through VCFs (see EVA-942)
> EVA-942 - Ignore Variant IDs submitted through VCFs

- README.md
> EVA-1421 Update travis configuration to Github Apps (eva-pipeline)

- pom.xml
- src/main/java/uk/ac/ebi/eva/pipeline/configuration/EvaPipelineBatchConfigurer.java
- src/main/java/uk/ac/ebi/eva/pipeline/configuration/MongoConfiguration.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/CalculateStatisticsTasklet.java
- src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/LoadStatisticsTasklet.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/JobParametersNames.java
- src/main/java/uk/ac/ebi/eva/pipeline/parameters/MongoConnection.java
- src/main/resources/application.properties
- src/test/java/uk/ac/ebi/eva/pipeline/configuration/jobs/steps/CalculateStatisticsStepTest.java
- src/test/java/uk/ac/ebi/eva/test/utils/JobTestUtils.java
EvaPipelineBatchConfigurer.java - More ceremony needed because of [change in the default serialization mechanism to Jackson](https://stackoverflow.com/a/49636389/2601814).
> EVA-2056 - Use updated OpenCGA library that uses Mongo 3.8 driver

- src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriter.java
> downgrade log message
