EBIvariation/eva-pipeline

project_initialization.py

with descriptions as:
"This project uses "funny quotes" to screw every one else"
we end up calling opencga like:
...opencga.sh ... -d "This project uses "funny quotes" to screw everyone else" ...
which gets interpreted as if the description was `-d  "This project uses funny"`and an extra parameter `quotes" to screw everyone else"` whithout arguments, what results in:
```
Was passed main parameter 'quotes" to screw everyone else"' but no main parameter was defined
```

fixed bug: escaping quotes on project description

---

README.md
examples/application.properties
examples/initialize-database.properties

External properties files don't need to define all the parameters, but they must be pointed to using `spring.config.location` (specific paths) instead of `spring.config.name` ("regex" that could end up excluding the internal application.properties).

Parameters not necessary in external properties files

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/VariantJobsArgs.java
src/main/java/uk/ac/ebi/eva/pipeline/io/GzipLazyResource.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/VariantAnnotConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/VariantConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/VariantStatsConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/deciders/EmptyFileDecider.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/VariantAnnotConfigurationTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/VariantConfigurationWorkflowTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantsAnnotCreateTest.java

- New decider implemented to check that there are variants to annotate before running VEP. If the VEP input file is empty then VEP and annotations load will not run.
- Removed extension .gz to the vep input file
EVA-444

optionalAnnotationSteps_EVA-444

---

src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantAnnotationMongoItemWriter.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantAnnotationWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/VariantAnnotConfigurationTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/VariantConfigurationTest.java

uk.ac.ebi.eva.pipeline.io.writers.VariantAnnotationMongoItemWriter#doWrite has been updated using now the mongo $addToSet option. In this way annotations from previous batches are not overwritten by the new one. Using $addToSet to avoid duplicates and $each to append all the annotations for each id. 
Tests updated accordingly
EVA-460

bugFix: multiple run of VariantAnnotationMongoItemWriter overwrite annotations

---

pom.xml

using either a local mongo 3.0 or 3.2 all tests pass.
a small manual load works as well.
diff of `mvn dependency:tree`:
```
[INFO] +- postgresql:postgresql:jar:9.1-901-1.jdbc4:compile        [INFO] +- postgresql:postgresql:jar:9.1-901-1.jdbc4:compile
[INFO] +- org.mongodb:mongo-java-driver:jar:2.14.2:compile      <
[INFO] +- org.springframework.data:spring-data-mongodb:jar:1.8.    [INFO] +- org.springframework.data:spring-data-mongodb:jar:1.8.
[INFO] |  +- org.springframework:spring-tx:jar:4.2.5.RELEASE:co    [INFO] |  +- org.springframework:spring-tx:jar:4.2.5.RELEASE:co
[INFO] |  +- org.springframework:spring-context:jar:4.2.5.RELEA    [INFO] |  +- org.springframework:spring-context:jar:4.2.5.RELEA
[INFO] |  +- org.springframework:spring-beans:jar:4.2.5.RELEASE    [INFO] |  +- …
```

EVA-477 using mongo-java-driver 2.14.2

---

src/main/java/uk/ac/ebi/eva/pipeline/Application.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/AnnotationJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/CommonJobStepInitialization.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/AnnotationLoaderStep.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantNormalizerStepTest.java

the first commit fixes the next bug, which makes the "load-genotyped-vcf" job unlaunchable: 
```
2016-10-06 15:54:36.945  INFO 18122 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'variantJob' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=genotypedVcfJob; factoryMethodName=variantJob; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJob.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; …
```

EVA-490 fix qualifier name colision in job and step names

---

src/main/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/listeners/VariantOptionsConfigurerListener.java

Before, we used a `@PostConstruct` to set some job-dependent configuration into VariantOptions, but it seems that all jobs are instantiated even if they are not used, so the configuration was overwritten.
affected configuration:
- includeSamples
- compressGenotypes
- calculateStats
- includeStats
Now, we use a job listener to set up those in a "beforeJobExecution" listener.

EVA-507 add VariantOptionsConfigurerListener to ensure samples are written

---

src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/AnnotationLineMapperTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/readers/AnnotationFlatFileReaderTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/readers/GeneReaderTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReaderTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/GeneWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VepAnnotationMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AnnotationJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/AnnotationLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/IndexesGeneratorStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PedLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsGeneratorStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantNormalizerStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepAnnotationGeneratorStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepInputGeneratorStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/processor/GeneFilterProcessorTest.java

Package `junit.framework` is deprecated but still used across a big part of our code. This PR replaces its occurrences with `org.junit`.

Using org.junit package

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/JobOptions.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/JobParametersNames.java
src/main/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReader.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/CommonJobStepInitialization.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/flows/AnnotationFlow.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/flows/PopulationStatisticsFlow.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/AnnotationLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/GeneLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/IndexesGeneratorStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/PedLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsGeneratorStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantNormalizerStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepAnnotationGeneratorStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepInputGeneratorStep.java
src/main/java/uk/ac/ebi/eva/utils/MongoDBHelper.java
src/test/java/uk/ac/ebi/eva/pipeline/configuration/CommonConfiguration.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VepAnnotationMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PedLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsGeneratorStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantNormalizerStepTest.java

Currently job parameters names are spread across the whole code using plain text strings. They have been moved into a new `JobParametersNames` class, listed as constants and used as such everywhere (automated replacement via `sed`).
It will also make easier to refer to them when validations are spread across multiple classes.

EVA-519 Job parameters names into constants

---

examples/application.properties
src/main/java/uk/ac/ebi/eva/pipeline/configuration/JobOptions.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/JobParametersNames.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsLoaderStep.java
src/main/java/uk/ac/ebi/eva/utils/MongoDBHelper.java
src/test/java/uk/ac/ebi/eva/pipeline/configuration/CommonConfiguration.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsLoaderStepTest.java
src/test/resources/annotation-loader-step.properties
src/test/resources/annotation.properties
src/test/resources/genotyped-vcf-workflow.properties
src/test/resources/genotyped-vcf.properties
src/test/resources/variant-aggregated.properties
src/test/resources/vep-input-generator-step.properties

Using `spring.data.mongodb.*` parameters to provide database connection details to the pipeline. I couldn't find a way to select the read preference, but it is not very relevant to the pipeline anyway.
`PopulationStatisticsLoaderStep` refactored to remove dependencies on OpenCGA manager classes. This allows it to use said Spring Data parameters.

EVA-572 Spring Data MongoDB jobparameters

---

src/test/java/uk/ac/ebi/eva/test/data/VariantData.java

The `VariantData` class didn't use the facilities provided by `TestFileUtils.getResource(String)`. This method is now used and the class made less verbose.

VariantData class using TestFileUtils

---

src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantAggregatedVcfFactory.java
src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactory.java
src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantAggregatedVcfFactoryTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfEVSFactoryTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfExacFactoryTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactoryTest.java

Before:
===
with a file of 10K samples:
total memory: around 2.2 GB
900K instances (20%) of String (most of them are "0|0")
900K instances (20%) of char[] (most of them are "0|0")
char[] + String occupy 25% the total memory
After:
===
removed useless code and using String::intern
the memory usage was reduced to a 77% of the previous memory usage.
the intern method is used to reuse the string of the genotype
from the pool of strings.
However, there are still lots of maps that have different pointers
pointing to the same strings.
with a file of 10K samples:
total memory: around 1.7 GB
1M instances (32%) of TreeMap$Entry
1M instances (46%) of TreeMap
these two occupy 78% the total memory

EVA-575 VariantVcfFactory: improve the memory usage by genotypes

---

src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriter.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriterTest.java

Indexes were created as
`db.variants.createIndex({ field : 1, background : 1 })`
instead of
`db.variants.createIndex({ field : 1 }, { background : 1 })`
This was why the indexes names ended with "\_background\_".

EVA-550 Ensuring variants collection indexes are created in background

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/VariantAnnotationReaderConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/AnnotationLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/GeneLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/AnnotationLoaderStepParametersValidator.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VariantLoaderStepParametersValidator.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VepInputGeneratorStepParametersValidator.java
src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/AnnotationLoaderStepParametersValidatorTest.java
src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VariantLoaderStepParametersValidatorTest.java
src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VepInputGeneratorStepParametersValidatorTest.java

- New parameter validator for AnnotationLoaderStep
- Added CONFIG_RESTARTABILITY_ALLOW and CONFIG_CHUNK_SIZE where missing
- To decide if in VepAnnotationGeneratorStepParametersValidator we have to check the CONFIG_RESTARTABILITY_ALLOW parameter since it is used outside in GenerateVepAnnotationStep.
EVA-551

Annotation loader step parameters validator eva 551

---

src/main/java/uk/ac/ebi/eva/pipeline/Application.java
src/main/java/uk/ac/ebi/eva/pipeline/model/PopulationStatistics.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/JobOptions.java

commits:
- fix bug: disabling the creation of (unused) popStats collection. There is a collection "populationStatistics" that we are not using yet, but the spring framework is preparing the indexes in that collection. 
- allow to tune the batch size for stats calculation. A big study (10K+ samples) was having memory troubles, so it is useful to use our `config.chunk.size` to also configure the batchsize in opencga's statistics calculation. if the memory usage is too high, setting a lower chunk size (such as 50) reduces the memory usage in the variants load step and the stats calculation step.

Minor stats improvement

---

src/main/java/uk/ac/ebi/eva/commons/models/data/VariantSourceEntity.java
src/main/java/uk/ac/ebi/eva/pipeline/io/readers/VcfHeaderReader.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantSourceEntityMongoWriterTest.java

With the change to a straightforward entity writing, the header dump in the "files" collection began to be written to "meta.variantFileHeader" instead of the correct "meta.header". This behavior has been reverted and a new test added.
The order of the `VariantSourceEntity` class attributes has been slightly modified to keep closer those that are related.

EVA-587 Fixed structure of "meta" field in "files" collection

---

src/main/java/uk/ac/ebi/eva/commons/models/converters/data/VariantToDBObjectConverter.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/MongoConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/NonAnnotatedVariantsMongoReaderConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/GeneWriterConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/VariantAnnotationWriterConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/VariantWriterConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/io/readers/MongoDbCursorItemReader.java
src/main/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReader.java
src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VepAnnotationMongoWriter.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/FileLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/IndexesGeneratorStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/PopulationStatisticsLoaderStep.java
src/main/java/uk/ac/ebi/eva/utils/MongoConnection.java
src/main/java/uk/ac/ebi/eva/utils/MongoDBHelper.java
src/test/java/uk/ac/ebi/eva/pipeline/ApplicationTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReaderTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/GeneWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/StatisticsMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantSourceEntityMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VepAnnotationMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/test/configuration/BaseTestConfiguration.java

When using OpenCGA converters to store `VariantSource` objects, dots in samples names were mapped to another character (this is a Mongo requirement).
This behavior is now replicated using the class `MappingMongoConverter` from Spring Data. In order to provide instances of this class to build `MongoTemplate` objects, `MongoDBHelper` must support being autowired, which involves:
* It must be annotated as `@Configuration`
* Those methods creating `MongoTemplate` objects can't be static anymore
* Reader / writer / tasklet-step configurations need to `@Import({ MongoDBHelper.class })`, to ensure they will work both in tests and stand-alone runs

EVA-587 Mapping dots in Mongo keys to another character

---

src/main/java/uk/ac/ebi/eva/pipeline/io/readers/VcfHeaderReader.java
src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriter.java
src/main/java/uk/ac/ebi/eva/pipeline/io/writers/VariantSourceEntityMongoWriter.java
src/main/java/uk/ac/ebi/eva/utils/MongoDBHelper.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantSourceEntityMongoWriterTest.java

A new unique, background index is now created in the "files" collection, on the following fields:
* File ID (`fid`)
* Filename (`fname`)
* Study ID (`sid`)
Both file ID and name because the file ID matches an ERZ, which can contain multiple files. We should consider renaming this field in the future.

EVA-587 Unique index in "files" collection

---

src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/CalculateStatisticsStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadStatisticsStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/PopulationStatisticsGeneratorStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/PopulationStatisticsLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/DatabaseParameters.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/InputParameters.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/OutputParameters.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/ParametersFromProperties.java
src/main/java/uk/ac/ebi/eva/utils/URLHelper.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsGeneratorStepTest.java

this is similar to https://github.com/EBIvariation/eva-pipeline/pull/70
the main change is in PopulationStatisticsGeneratorStep, where JobOptions is not used anymore. Instead, we use the containers that autowire jobParameters (InputParameters, OutputParameters, DatabaseParameters).
Tests changed accordingly to pass JobParameters to the launched job/step.

EVA-596 Use JobParameters in statistics generation step

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/MongoConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/NonAnnotatedVariantsMongoReaderConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/VariantAnnotationReaderConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/GeneWriterConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/VariantAnnotationWriterConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/VariantWriterConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReader.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/CalculateStatisticsStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/CreateDatabaseIndexesStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/GenerateVepAnnotationStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadStatisticsStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/FileLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/tasklets/IndexesGeneratorStep.java
src/test/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReaderTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/GeneWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/StatisticsMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VariantSourceEntityMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/io/writers/VepAnnotationMongoWriterTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/test/configuration/BaseTestConfiguration.java
src/test/java/uk/ac/ebi/eva/test/configuration/BatchTestConfiguration.java

MongoConfiguration now is a configuration and is also used with autowiring which is not consistent.
MongoConfiguration now has been refactored so that MongoOperation is injected into the spring context with StepScope. This way the configuration of reader and writers can be simplified. The code has been separated so that we can use static methods from MongoConfigurations and use them in tests where we need to create specific conections.

EVA-634 Refactor of MongoConfiguration

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/writers/VariantWriterConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/AnnotationLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/CalculateStatisticsStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/CreateDatabaseIndexesStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/GeneLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/GenerateVepAnnotationStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadStatisticsStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStep.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepInputGeneratorStep.java
src/main/java/uk/ac/ebi/eva/pipeline/listeners/VariantOptionsConfigurerListener.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/JobOptions.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/ParametersFromProperties.java
src/main/java/uk/ac/ebi/eva/utils/TaskletUtils.java
src/test/java/uk/ac/ebi/eva/pipeline/ApplicationTest.java

Removed all unused elements. 
Moved configuration variables that were in variant pipeline that were only used as boolean elements to JobOptions getters.
Moved chunk size and restartability from pipelineOptions to JobOptionsGetters.
PipelineOptions only retains the skip tests pending further refactoring.

Refactored JobOptions to remove all innecesary injections and elements

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/JobExecutionDeciderConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/deciders/SkipStepDecider.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/flows/AnnotationFlowOptional.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/flows/PopulationStatisticsOptionalFlow.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/JobOptions.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/ParametersFromProperties.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
src/test/java/uk/ac/ebi/eva/utils/EvaJobParameterBuilder.java

SkipStepDecider now receives a jobParameterName that is queried to decide if it has to skip the next step. This is done without @StepScopes or @JobScopes as it seems this class was being executed by a thread without the bean scope. Thus we use the JobExecution that the system passes in the decide function to retrieve the value of the parameter.

Refactored skip parameters and removed them from jobOptions.

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/readers/NonAnnotatedVariantsMongoReaderConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReader.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/VepInputGeneratorStep.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/AnnotationParameters.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/InputParameters.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/AggregatedVcfJobParametersValidator.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/job/GenotypedVcfJobParametersValidator.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/AnnotationLoaderStepParametersValidator.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VepAnnotationGeneratorStepParametersValidator.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VepInputGeneratorStepParametersValidator.java
src/test/java/uk/ac/ebi/eva/pipeline/io/readers/NonAnnotatedVariantsMongoReaderTest.java
src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/AnnotationLoaderStepParametersValidatorTest.java
src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VepAnnotationGeneratorStepParametersValidatorTest.java
src/test/java/uk/ac/ebi/eva/pipeline/parameters/validation/step/VepInputGeneratorStepParametersValidatorTest.java

This PR improves the NonAnnotatedVariantsReader, and belongs to a bigger refactor whose purpose is to have the annotation flow like this:
- annotation flow:
- GenerateAnnotationStep
- NonAnnotatedVariantsReader ---**current PR**---
- VepAnnotationFileWriter
- AnnotationLoaderStep
- VariantAnnotationReader
- VariantAnnotationWriter

EVA-705 Modify NonAnnotatedVariantsReader to return java objects instead of DBObject

---

src/main/java/uk/ac/ebi/eva/pipeline/io/VepProcess.java

It seems that when VEP hangs (due to the unnoticed death of some of its inner threads probably), we continue writing into the standard input (stdin) of VEP, but it won't write anything more, nor will consume more data from its stdin, so eventually the buffers get filled and it turns out that in the OutputStream class the `write` method can also block (just as `read`), but doesn't provide any "write with timeout" method.
So, what we have to do is keep track of the time we spent writing, and stop the step if the timeout is reached.

EVA-683 Detect when VEP hangs

---

src/main/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/AnnotationJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/DatabaseInitializationJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/DropStudyJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJob.java
src/main/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJob.java
src/main/java/uk/ac/ebi/eva/pipeline/parameters/NewJobIncrementer.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AggregatedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/AnnotationJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/DropStudyJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/GenotypedVcfJobWorkflowTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/PopulationStatisticsJobTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/AnnotationLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/AnnotationMetadataStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/DropFilesByStudyStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/DropSingleStudyVariantsStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/GenerateVepAnnotationStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/IndexesGeneratorStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/LoadFileStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsGeneratorStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PopulationStatisticsLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/PullFilesAndStatisticsByStudyStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/jobs/steps/VariantLoaderStepTest.java
src/test/java/uk/ac/ebi/eva/pipeline/runner/EvaPipelineJobLauncherCommandLineRunnerTest.java
src/test/java/uk/ac/ebi/eva/test/utils/JobTestUtils.java
src/test/java/uk/ac/ebi/eva/utils/EvaCommandLineBuilder.java

The second time a job is launched, it should only reuse parameters (that can be overwritten with the current parameters) if the job failed. Otherwise, only the new parameters should be used. 
A solution is to implement our own JobParameters incrementer, because it will be used here https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/batch/JobLauncherCommandLineRunner.java#L158 (only if the job is not stopped or failed)

EVA-741 The parameters from completed executions should not be reused

---

pom.xml

Direct pushes to develop are prevented, so we can push this pull reques with a fast-forward

Bumped version to 2.0-beta5-SNAPSHOT for next development cycle

---

src/main/java/uk/ac/ebi/eva/pipeline/configuration/io/readers/VariantsMongoReaderConfiguration.java
src/main/java/uk/ac/ebi/eva/pipeline/io/readers/VariantsMongoReader.java
src/test/java/uk/ac/ebi/eva/pipeline/io/readers/VariantsMongoReaderTest.java

When a big study is loaded and only a small amount of variants are pending to annotate, the search could timeout. In order to reduce the chance of this happening, an additional filter has been added to `VariantsMongoReader`. Now it restricts by file (being loaded) in addition to the study.
I'm not sure about the nesting (if no study is specified it doesn't matter whether the file is) as a concept, but in terms of performance is the only thing that makes sense...

EVA-880 Reduce chance of timeouts in (re-)annotation search

---

examples/initialize-database.properties

The purpose of this PR is to add `db.collections.features.name` to the `initialize-database.properties` which is a required property to run the job `init-database-job`

Added feature property to initialize-database.properties

---

src/main/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactory.java
src/test/java/uk/ac/ebi/eva/pipeline/io/mappers/VariantVcfFactoryTest.java

Unfortunately `eva-pipeline` is not using the `variation-commons` library and have its own implementation for the Readers although they seem very similar. We should probably refactor this repo and use variation commons. See [EVA-2300](https://www.ebi.ac.uk/panda/jira/browse/EVA-2300)

EVA-2287 Avoid removing chr prefix

---

src/main/java/uk/ac/ebi/eva/pipeline/jobs/steps/processors/VepAnnotationProcessor.java

Skip empty VEP output from being processed by returning null. See [here](https://docs.spring.io/spring-batch/docs/current/reference/html/domain.html#item-reader).

EVA-1893 - Ensure that annotation process does not fail due to empty VEP output

---

src/main/java/uk/ac/ebi/eva/pipeline/runner/CommandLineRunnerUtils.java
src/main/java/uk/ac/ebi/eva/pipeline/runner/EvaPipelineJobLauncherCommandLineRunner.java
src/test/java/uk/ac/ebi/eva/pipeline/runner/EvaPipelineJobLauncherCommandLineRunnerTest.java
src/test/java/uk/ac/ebi/eva/test/utils/GenotypedVcfJobTestUtils.java

Fix resumability of jobs by adding `runId` to job params when appropriate (see [here](https://github.com/EBIvariation/eva-accession/blob/0cdce9669b66bb82237f51defe85578641ab04ed/eva-accession-core/src/main/java/uk/ac/ebi/eva/accession/core/runner/CommandLineRunnerUtils.java) and [here](https://github.com/EBIvariation/eva-accession/blob/0cdce9669b66bb82237f51defe85578641ab04ed/eva-accession-clustering/src/main/java/uk/ac/ebi/eva/accession/clustering/runner/ClusteringCommandLineRunner.java#L124) for the same logic in eva-accession).

EVA-2580 - Fix for resumability of jobs

---

.gitlab-ci.yml

A small change was made in an earlier PR to generate a jar that can be added as a dependency to other projects. It was being used as a dependency in the Groovy project for remediation of ref/alt.
This means the artifact name needs to be changed for deployment as the pipeline is not able to find the generated artifact

Update gitlab-ci artifact path for deployment
